kubernetes_deploy:
  image: nexus.nico-dreher.de:8084/kubectl:latest
  stage: deploy
  script:
    - mkdir ~/.kube/
    - echo ${kube_config} | base64 -d > ~/.kube/config
    - kubectl apply -f handycrab-deployment.yaml
  only:
    - master
  environment:
    name: production
    url: http://handycrab.nico-dreher.de