stages:
  - build
  - test
  - push
  - deploy


variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - handycrab-api/target/
    - handycrab-ear/target/
    - handycrab-server/target/
    - handycrab-webapp/target/

build:
  stage: build
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean compile package -Dmaven.test.skip=true
  artifacts:
    paths:
      - handycrab-ear/target/handycrab-ear-1.0-SNAPSHOT.ear

test:
  stage: test
  image: maven:latest
  variables:
    mongo_database: handycrab
  script:
    - mvn $MAVEN_CLI_OPTS -pl handycrab-server,handycrab-api test
  artifacts:
    reports:
      junit:
        - handycrab-server/target/surefire-reports/TEST-*.xml
        - handycrab-server/target/failsafe-reports/TEST-*.xml

deploy:
  stage: push
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master

docker_deploy:
  image: docker:19.03.1
  stage: push
  services:
    - docker:19.03.1-dind
  before_script:
    #- docker login -u $NEXUS_USER -p $NEXUS_PASS nexus.nico-dreher.de:8082
    - docker login -u $NEXUS_USER -p $NEXUS_PASS nexus.nico-dreher.de:8083
  script:
    - wget https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/3.12.2/mongo-java-driver-3.12.2.jar -P wildfly/modules/system/layers/base/org/mongodb/main/
    - docker pull nexus.nico-dreher.de:8083/handycrab:latest || true
    - docker build --cache-from nexus.nico-dreher.de:8084/handycrab:latest --tag nexus.nico-dreher.de:8083/handycrab:1.0-SNAPSHOT --tag nexus.nico-dreher.de:8083/handycrab:latest .
    - docker push nexus.nico-dreher.de:8083/handycrab:1.0-SNAPSHOT
    - docker push nexus.nico-dreher.de:8083/handycrab:latest
  only:
    - master

kubernetes_deploy:
  image: 
    name: nexus.nico-dreher.de:8084/kubectl:latest
    entrypoint: [""]
  stage: deploy
  script:
    - mkdir ~/.kube/
    - echo $kube_config | base64 -d > ~/.kube/config
    - kubectl apply -f handycrab-namespace.yaml
    - kubectl delete secret -n handycrab mongo-connection
    - kubectl create secret generic -n handycrab mongo-connection --from-literal=connection="$mongo_connection"
    - kubectl apply -f handycrab-deployment.yaml
    - kubectl rollout restart -n handycrab deployment/handycrab
  only:
    - master